### ISSUE TITLE
Reference previous papers from Sai

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#42]
You need to reference at least three of the key papers on Sloop that Sai has published.  Reference them for the first time here, when you first mention Sloop:

https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L42-L43

**Comment by rwestlund** [comment]
This paragraph also needs to reference Sai's papers.

https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap2.tex#L10-L13

**Comment by rwestlund** [comment]
Navi, this isn't resolved at all. You only added the most recent paper.  There are several older ones from Sai about relevance feedback that you're building on.  Cite those too.

**Comment by vanallen** [comment]
Please let me know if this list looks good to you.
- [x] **Cited** this
  
  > C. Finn, J. Duyck, A. Hutcheon, P. Vera, J. Salas and S. Ravela Relevance Feedback in Biometric Retrieval of Animal Photographs, MCPR 2014(to appear)
- [x] **Cited** this
  
  > Duyck, J., Finn, C., Hutcheon, A., Vera, P., Salas, J., Ravela, S.: Sloop: A Pattern Retrieval Engine for Individual Animal Identification. Pattern Recognition (2014)
- [ ] **Will be cited** this. Face recognition with differential features and gaussian filtering. Suggest the use of relevance feedback _(motivation)_ 
  
  > Ravela, S.: On Multi-scale Differential Features and their Representations for Recognition and Retrieval. PhD thesis, University of Massachusetts at Amherst (2002)
- [ ] **Will be cited** Sloop for marble salamander with relevance feedback _(motivation)_
  
  > Ravela, S., Yang, C., Runge, J., Gamble, L., McGarigal, K., Chesser, M.: Visual Recapture for Movement Ecology at Interannual Timescales. In: Workshop on Visual Observation and Analysis of Animal and Insect Behavior (2008)
- [x] No relevance feedback. **Cited** this because it describes older version of sloop
  
  > Ravela, S., Duyck, J., Finn, C.: Vision-Based Biometrics for Conservation. In: Carrasco-Ochoa, J.A., Martínez-Trinidad, J.F., Rodríguez, J.S., di Baja, G.S. (eds.) MCPR 2012. LNCS, vol. 7914, pp. 10–19. Springer, Heidelberg (2013)CrossRef

---
- [ ] No relevance feedback. This uses PCA.
  Marbled Salamander, which is not deployed on current sloop
  
  > Gamble, L., Ravela, S., McGarigal, K.: Multi-scale Features for Identifying Individuals in Large Biological Databases: An Application of Pattern Recognition Technology to the Marbled Salamander Ambystoma opacum. Journal of Applied Ecology 45(1), 170–180 (2008)
- [ ] No relevance feedback. This uses PCA.
  
  > Ravela, S., Gamble, L.: On Recognizing Individual Salamanders. In: Asian Conference on Computer Vision, vol. 2, pp. 741–747 (2004)
- [ ] No relevance feedback. This implements PCA and scale-cascade
  
  > Yang, C., Ravela, S.: Spectral Control of Viscous Alignment for Deformation Invariant Image Matching. In: International Conference on Computer Vision, vol. 1, pp. 1303–1310 (2009)

**Comment by vanallen** [comment]
I have added previous Sai's papers to the intro (chap1) and related work (chap2.)

**Comment by rwestlund** [comment]
Much better :)
